_sector = missionNamespace getVariable ["sectorOldDebris", objNull];
_sector setVariable ["sectorName", "Old debris", true];
_sector setVariable ["max", 3, true];
_sector setVariable ["min", 1, true];
_sector setVariable ["maxStatic", 2, true];
_sector setVariable ["waypoints", 4, true];
_sector setVariable ["value", 1, true];
_sector setVariable ["sector_sectorOldDebris_controller", west];
_manpowerMarker = "sectorOldDebris_manpowerMarker";
_manpowerMarker setMarkerAlpha 0;

_sector = missionNamespace getVariable ["sectorNaxok", objNull];
_sector setVariable ["sectorName", "Naxok", true];
_sector setVariable ["max", 5, true];
_sector setVariable ["min", 2, true];
_sector setVariable ["maxStatic", 3, true];
_sector setVariable ["waypoints", 8, true];
_sector setVariable ["value", 2, true];
_sector setVariable ["sector_sectorNaxok_controller", west];
_manpowerMarker = "sectorNaxok_manpowerMarker";
_manpowerMarker setMarkerAlpha 0;

_sector = missionNamespace getVariable ["sectorTuan", objNull];
_sector setVariable ["sectorName", "Tuan", true];
_sector setVariable ["max", 6, true];
_sector setVariable ["min", 2, true];
_sector setVariable ["maxStatic", 3, true];
_sector setVariable ["waypoints", 4, true];
_sector setVariable ["value", 2, true];
_sector setVariable ["sector_sectorTuan_controller", west];
_manpowerMarker = "sectorTuan_manpowerMarker";
_manpowerMarker setMarkerAlpha 0;

_sector = missionNamespace getVariable ["sectorNaboFarms", objNull];
_sector setVariable ["sectorName", "Nabo Farms", true];
_sector setVariable ["max", 3, true];
_sector setVariable ["min", 1, true];
_sector setVariable ["maxStatic", 2, true];
_sector setVariable ["waypoints", 4, true];
_sector setVariable ["value", 1, true];
_sector setVariable ["sector_sectorNaboFarms_controller", west];
_manpowerMarker = "sectorNaboFarms_manpowerMarker";
_manpowerMarker setMarkerAlpha 0;

_sector = missionNamespace getVariable ["sectorNaboCamp", objNull];
_sector setVariable ["sectorName", "Nabo Camp", true];
_sector setVariable ["max", 20, true];
_sector setVariable ["min", 10, true];
_sector setVariable ["maxStatic", 8, true];
_sector setVariable ["waypoints", 4, true];
_sector setVariable ["value", 4, true];
_sector setVariable ["sector_sectorNaboCamp_controller", west];
_manpowerMarker = "sectorNaboCamp_manpowerMarker";
_manpowerMarker setMarkerAlpha 0;

_sector = missionNamespace getVariable ["sectorNaboFair", objNull];
_sector setVariable ["sectorName", "Nabo Fair", true];
_sector setVariable ["max", 10, true];
_sector setVariable ["min", 5, true];
_sector setVariable ["maxStatic", 6, true];
_sector setVariable ["waypoints", 4, true];
_sector setVariable ["value", 3, true];
_sector setVariable ["sector_sectorNaboFair_controller", west];
_manpowerMarker = "sectorNaboFair_manpowerMarker";
_manpowerMarker setMarkerAlpha 0;

_sector = missionNamespace getVariable ["sectorThat", objNull];
_sector setVariable ["sectorName", "That", true];
_sector setVariable ["max", 10, true];
_sector setVariable ["min", 4, true];
_sector setVariable ["maxStatic", 5, true];
_sector setVariable ["waypoints", 6, true];
_sector setVariable ["value", 3, true];
_sector setVariable ["sector_sectorThat_controller", west];
_manpowerMarker = "sectorThat_manpowerMarker";
_manpowerMarker setMarkerAlpha 0;